- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: check robouser exist or not
    ansible.builtin.command: id roboshop
    register: user_output
    ignore_errors: true

  - name: print variable
    ansible.builtin.debug:
     msg: "user ouput {{user_output}}"

  - name: print exit status or return code
    ansible.builtin.debug:
     msg: "status is: {{user_output.rc}}"
  
  - name: create user
    ansible.builtin.user:
      name: roboshop
    when: user_output.rc != 0 




