- name: loopforinstallation
  hosts: localhost
  become: yes
  tasks:
  - name: package installation
    ansible.builtin.package:
      name: "{{item}}"
      state: absent

    loop:
    - git
    - gcc
    - make