- name: PLAY1
  hosts: localhost
  tasks:
    - name: play1-task1
      ansible.builtin.debug:
       msg: "HELO FROM PLAY1 and TASK1"

- name: PLAY2
  hosts: localhost
  tasks:
    - name: play2-task2
      ansible.builtin.debug:
        msg: "HELLO FROM PLAY2 and TASK2"