- name: package installation
  host: web
  task:
   -name: ngnix installation
      ansible.builtin.package:
        name: nginx
        state: present
   -name: run ngnix service
      ansible.builtin.service:
        name: nginx
        state: started


    