- name: ping playbook
  hosts: web
  tasks:
  - name: ping the server
    ansible.builtin.ping:

- name: ping playbook
  hosts: prod
  tasks:
  - name: ping the server
    ansible.builtin.ping:

     