- name: variable with prompt
  hosts: localhost
  vars_prompt:
    - name: prompting username
      prompt: "please enter username"
      private: false
    - name: prompting password
      prompt: "please enter password"
      private: true
  tasks:
    - name: print and chcek the values
      ansible.builtin.debug:
        msgs: "username is {{USERNAME}}, password is {{PASSWORD}}"
