- name: variables
  hosts: localhost
  vars:
    NAME: "BHARATH RAPAKA"
    COURSE: "DEVOPS"
    DESIGNATION: "DEVOPS ENGINEER"
  tasks:
  - name: adding variables
    ansible.builtin.debug:
      msgs: "helo this is {{NAME}}, practing {{COURSE}} and become {{DESIGNATION}}"
