- name: variable with prompt
  hosts: localhost
  vars_prompt:
    - name: USERNAME
      prompt: "please enter username"
      private: false
    - name: PASSWORD
      prompt: "please enter password"
      private: true
  tasks:
  - name: print and check the values
    ansible.builtin.debug:
     msg: "username is {{USERNAME}}, password is {{PASSWORD}}"
