- name: variablewithprompt
  hosts: localhost
  vars_prompt:
   - name: USERNAME
     prompt: "enter the username"
     private: false
   - name: PASSWORD
     prompt: "enter the password"
     private: true
  tasks:
  - name: print and check the value
    ansible.builtin.debug:
     msg: "username is {{USERNAME}} and password is {{PASSWORD}}"
